### ISSUE TITLE
Error when I enable the extension 'ckanext-scheming'

### ISSUE THREAD

**Issue by rsalas82** [open-data/ckanext-scheming#21]
Hi Ian.

I have developed some opendata portals in Spain (e.g. https://datos.upo.gob.es) which use CKAN as a backend with Wordpress + Wijmo as a frontend. I have a portal that needs multilingual support and I have solved this problem by adding extra fields in the dataset form following the CKAN extension docs, but I would like to try out your ckanext-fluent extension.

I have installed ckanext-scheming, but when I activate the plugin and I access the server CKAN shows the following error:

<pre>
File "/usr/lib/ckan/default/src/ckanext-scheming/ckanext/scheming/plugins.py", line 6, in <module>
   from ckan.plugins.toolkit import (get_validator, get_converter,
ImportError: cannot import name get_validator
</pre>

What am I doing wrong?

**Comment by wardi** [comment]
Check out the requirements for running scheming https://github.com/open-data/ckanext-scheming#requirements . I expect you're just running an incompatible ckan.

**Comment by rsalas82** [comment]
I have tried both version 2.2.1 as version 2.3, and both have given me the same error.
