### ISSUE TITLE
'dict object' has no attribute

### ISSUE THREAD

**Issue by Hoedic** [open-data/ckanext-scheming#43]
I have an error when opening a dataset generated by a harvester: ckan complains that the author_email is missing.

Seems that it's ckanext-scheming that triggers the error.

See error trail: http://pastebin.com/Ssneu6sP

The harvester used is the ckanext-dcat used to harvest a DCAT-RDF file coming build using the following example: https://github.com/ckan/ckanext-dcat/blob/master/examples/catalog_datasets_list.rdf

When the harvester creates the datasets, it does not provide/create a author_email field. If I edit a dataset and resave it (without changing anything), the field is created and the error does not appear anymore.

Here is an API output for 2 dataset generated by the harvester: the first one has author_email (it has been edited/saved) while the second is directly how produced by the harvester

http://pastebin.com/Vt78AgmX

**Comment by wardi** [comment]
IIUC the ckan harvester overrides the schema that scheming uses, so this will probably take some work or changes to the ckan harvester.

**Comment by wardi** [comment]
On second thought we can probably just make a change to the scheming display snippet logic to gracefully handle missing data.

**Comment by Hoedic** [comment]
@wardi : Yes, I ended up having the same issue while uploading datasets via ckanapi. If your extension can gracefully support missing data, it is probably more solid than expecting that any process that can inject some data outside of the web UI process will comply with a way of doing.
