### ISSUE TITLE
When displaying additionnal info, should use the value and not the id

### ISSUE THREAD

**Issue by Hoedic** [open-data/ckanext-scheming#46]
Sometimes, the data provided for scheming is a list with the form (id, value), mainly in the case of a value list.

For example, to declare an update frequency, one has to provide a standardized value (eg. freq:irregular), but we want to display something more fitted for human (e.g "Ponctuel").

Given how things are working it is far from straighforward. Since the place where it is the main concerns is when not using english, at least the display should use the translation feature.

**Comment by wardi** [comment]
Can you used a fixed vocabulary like https://github.com/open-data/ckanext-scheming#choices ? That displays the label but stores the "value" for use by the API and form submissions. it can also have multiple languages in the "label" field

**Comment by Hoedic** [comment]
Indeed! Is there a way to specify the "selected" value in the config 
file? For the update frequency, we would like to have "irregular" as the 
default value.

**Comment by wardi** [comment]
I haven't implemented default values for fields yet. That would just take a couple more lines in the form snippet, though

**Comment by benjaminlaot** [comment]
As a workaround you can set the field  "required" to True and place the value that you want "irregular "in the first position of your list. It will be  the default value.

**Comment by Hoedic** [comment]
Yes @benjaminlaot, I ended seeing this behaviour on one of the "select" item I've done later and made mandatory. This way of doing sound logical: usually we want to put a default value because the field is indeed mandatory.
