### ISSUE TITLE
Add schema field in search

### ISSUE THREAD

**Issue by Hoedic** [open-data/ckanext-scheming#47]
Is there a specific need to add a schemed field in the search feature of CKAN?

I've added a field that I need searchable:

```
        {
            "field_name": "featured_dataset",
            "label": "Jeu de données vedette",
            "preset": "multiple_checkbox",
            "choices": [
                {
                    "label": "Oui",
                    "value": "is_featured"
                }
            ],
            "help_text": "Affiche le jeu de données sur la page d'accueil"
        }
```

I've update the solr schema.xml:

```
    <field name="tags" type="string" indexed="true" stored="true" multiValued="true"/>
    <field name="groups" type="string" indexed="true" stored="true" multiValued="true"/>
    <field name="featured_dataset" type="string" indexed="true" stored="true" multiValued="true"/>

    <field name="capacity" type="string" indexed="true" stored="true" multiValued="false"/>
```

Then reloaded everything.

I'm no SOLR expert, but I would expect a search query like `q=featured_dataset:is_featured` to work, but it does not. `q=is_featured` works, but clearly it's not specific enough.

**Comment by wardi** [comment]
scheming stores new dataset fields as extras which are indexed in solr a bit differently. try searching in the field `extras_featured_dataset`. You're using the `multiple_checkboxes` preset so the value would be `["Oui"]` when that checkbox is checked.

**Comment by wardi** [comment]
Make that `["is_featured"]` (the value will be stored, not the label)

**Comment by Hoedic** [comment]
Working with `q=extras_featured_dataset:is_featured`!
