### ISSUE TITLE
Changing /dataset link

### ISSUE THREAD

**Issue by jguo144** [open-data/ckanext-scheming#53]
What are steps are needed to switch links from the default schema to a new schema?
Is it just a matter of changing a few templates to link  "/catalog", instead of "/dataset"?

**Comment by wardi** [comment]
Yes, that should be it. You could also try adding a

```python
    def is_fallback():
        return True
```

to the plugin class if this will be your default dataset type. If that helps we should add it to scheming and add a configuration option for it.
