### ISSUE TITLE
Document / make easier to run the tests locally

### ISSUE THREAD

**Issue by amercader** [open-data/ckanext-scheming#63]
The `ini` files are located on the tests folder, which is fine but not where generally extensions have them, so worth mentioning on the README.
The `use = config:../../../links/ckan/test-core.ini` has a links folder not present on a default set up, I guess this is set for Travis?
There are two ini files, what's `test_subclass.ini` for?

**Comment by wardi** [comment]
test_subclass.ini is an alternate config for checking that we can subclass the SchemingDatasets plugin class and use that subclass as a plugin. It's just one more level of customization if someone needs to do something that the schema can't provide.

The links hacks are.. hacky. Please offer suggestions to clean them up if you can.

**Comment by amercader** [comment]
Can we just assume ckan and ckanext-scheming are side by side and use `use = config:../ckan/test-core.ini`?

It's what we normally use, eg:

https://github.com/ckan/ckanext-harvest/blob/master/test-core.ini

https://github.com/ckan/ckanext-spatial/blob/master/test.ini

**Comment by wardi** [comment]
Yeah that sounds better
