### ISSUE TITLE
Notes (description) not showing up on dataset page

### ISSUE THREAD

**Issue by amercader** [open-data/ckanext-scheming#64]
Because [this check](https://github.com/open-data/ckanext-scheming/blob/5ae6afdf0527a7458cf7b93e950b2233b59343be/ckanext/scheming/templates/scheming/package/read.html#L12) is wrong. AFAICT what you are getting from the helper already is `schema.dataset_fields`, which is a list of `[{'field_name': 'notes',... }]`.

**Comment by wardi** [comment]
Good catch. I was trying to hide the notes if the user's schema had no notes field. I'll need to add a loop or helper to pull the field out by name.

**Comment by wardi** [comment]
fixed via #65
