### ISSUE TITLE
error-explanation alert type is always empty? 

### ISSUE THREAD

**Issue by ckylape** [open-data/ckanext-scheming#70]
When using the [default errors template](https://github.com/open-data/ckanext-scheming/blob/master/ckanext/scheming/templates/scheming/snippets/errors.html), it seems that `type` and `classes` are always empty which leaves the resulting output as:

```html
<div class="error-explanation alert alert- ">
```

The [macros/form.html errors macro](https://github.com/ckan/ckan/blob/master/ckan/templates/macros/form.html#L287-L298) allows both to be specified, but then you lose the custom labels etc. I don't need the styling to change so I just created a custom template and set it to:
```html 
<div class="error-explanation alert alert-error">
````

**Comment by wardi** [comment]
good catch. @ckylape Care to submit that fix? I doubt there are many people customizing the class of the error.
