### ISSUE TITLE
hook needed to run validators

### ISSUE THREAD

**Issue by marcfor** [open-data/ckanext-scheming#71]
I ran into a problem when trying to create a dataset with resource fields defined in the schema.  I have a validator that builds the name field, but the validator doesn't get run in time. When the browser tries to go to the form which would allow me to enter a resource, it fails because it can't complete the url since it's missing the name of the dataset I want to create.

https://github.com/ckan/ckan/blob/release-v2.2.3/ckan/controllers/package.py#L618

**Comment by marcfor** [comment]
I have a similar issue with the URL field.  I want to make the url field in a resource a fluent text field, but when I submit the resource, CKAN checks that there is a value provided to the URL field before scheming has mangled the fluent fields into one url field. CKAN then complains that no url was provided.

**Comment by wardi** [comment]
@marcfor why not try getting it working without the fancy name validator. Just a normal text field will be fine for loading the data for now, right?

**Comment by wardi** [comment]
@marcfor also, please paste the traceback you're getting and link to the schema you're using

**Comment by marcfor** [comment]
@wardi I had worked around the issue with the name field as you suggested by declaring it as a text field in the schema.  It works for now.

**Comment by wardi** [comment]
@marcfor please remind me to look into this tomorrow

**Comment by marcfor** [comment]
@wardi Unfortunately (or fortunately, depending how you look at it) I'm unable to reproduce the problem with the create name validator.  Not sure why, maybe my VM was in a weird state when I had the problem.

As for the resource URL issue, we decided not to have it as a fluent field and create a separate resource for the French and English (at least for now).

**Comment by wardi** [comment]
yes, I think separate resources makes more sense. Closing for now, but let me know if it pops up again
