### ISSUE TITLE
Group/organization form seem not to work

### ISSUE THREAD

**Issue by metaodi** [open-data/ckanext-scheming#72]
The scheming for datasets works like a charm, but for groups and organization only the about page seems to be changed. I can save additional fields via the API, but the form to add or edit a group/organization do not show the fields defined in the schema.

How does that work?

**Comment by wardi** [comment]
@metaodi scheming for groups and orgs is only partially implemented. I didn't finish the core ckan changes required in time for 2.3 but 2.4 might now have the changes we need to implement the custom form like the one for datasets. Do you have any time to finish off the missing templates?

**Comment by wardi** [comment]
See also #29

**Comment by brew** [comment]
I'm looking at this at the moment. I'm a bit stuck on the group_show and extras. Should extras be converted to first-class values by the validation when using group_show? They don't seem to be, though I could be doing something wrong.

**Comment by wardi** [comment]
Yes, IIUC extras in groups should work like package extras, needing to be converted to a list of extras objects (not like resource extras)

**Comment by brew** [comment]
Sorry - I meant: does scheming convert group extras automatically (like it does for packages)? It looks like it should, but it doesn't work for me.

**Comment by wardi** [comment]
fixed by #83 and #84
