### ISSUE TITLE
Built-in date preset results in unix timestamps when combined with plain-text solr fields.

### ISSUE THREAD

**Issue by TkTech** [open-data/ckanext-scheming#78]
An input string of "2014-03-27" being loaded into a plain-text solr field (type="string" or type="text" in the schema) will result in a plain-text string containing the unix timestamp of "2014-3-27" instead of a plain-text string containing "2014-03-27".

This only occurs when using the built-in date preset. Removing the preset results in "2014-03-27" being stored.

**Comment by wardi** [comment]
this must be related to ckan's built-in `isodate` validator that converts the value to a datetime. That doesn't explain why your dates are being formatted that way, though, are you formatting them yourself with str.format() or similar?

datetime objects are handled by ckan's "dictization" code but are probably not handles by the indexing code unless your field names ends with `_date`

Closing for now, please let me know if you still think this is a bug in scheming
