### ISSUE TITLE
500 Server Error -- repeated posts to Solr when creating custom dataset

### ISSUE THREAD

**Issue by slnovak** [open-data/ckanext-scheming#85]
Hi,

I'm hitting a 500 Server error when trying to create an instance of my custom dataset.

### Configuration ###

+ CKAN v 2.4.1
+ ckanext-scheming @969995b
+ My [schema](https://gist.github.com/slnovak/309efcf508da1c38b489)

### Steps to reproduce ###

+ Create a fresh CKAN instance with ckanext-scheming
+ Visit the form to create the new dataset (i.e., `http://192.168.99.100/beataml_patient/new`)
+ Fill out the form, get to the next page to add resources, click next...
+ :boom:
+ Visiting `http://192.168.99.100/beataml_patient/test-patient` shows that it's a "DRAFT".
+ Clicking "Modify" takes me back to the same "new" form.
+ Rinse, repeat.

### Solr logs ###

I see that there are calls being made to Solr which could be from [`process_solr`](https://github.com/ckan/ckan/blob/39e537e88231dc793616bdd3f2440b318c85dcb9/ckan/logic/action/update.py#L1156-L1171).

```
solr_1       | 1021391 [qtp1894627749-17] INFO  org.apache.solr.core.SolrCore  – [ckan] webapp=/solr path=/select params={q=name:"test-patient"+OR+id:"test-patient"&wt=json&fq=site_id:"default"&rows=1} hits=1 status=0 QTime=0
solr_1       | 1021401 [qtp1894627749-15] INFO  org.apache.solr.core.SolrCore  – [ckan] webapp=/solr path=/select params={q=name:"test-patient"+OR+id:"test-patient"&wt=json&fq=site_id:"default"&rows=1} hits=1 status=0 QTime=1
solr_1       | 1021409 [qtp1894627749-14] INFO  org.apache.solr.core.SolrCore  – [ckan] webapp=/solr path=/select params={q=name:"test-patient"+OR+id:"test-patient"&wt=json&fq=site_id:"default"&rows=1} hits=1 status=0 QTime=0
etc...
```

There's nothing being generated in CKAN logs.

Do you have any thoughts as to what could be causing this?

Thanks!

**Comment by wardi** [comment]
try removing the schema_fields key from your schema completely if you don't have any resources
https://github.com/open-data/ckanext-scheming/blob/969995b/ckanext/scheming/templates/scheming/package/snippets/package_form.html#L26

**Comment by slnovak** [comment]
:+1:

Thanks! That resolved the issue.
