### ISSUE TITLE
Display snippet for external link

### ISSUE THREAD

**Issue by florianm** [open-data/ckanext-scheming#92]
Since display snippet link.html seems to link back to the dataset page, it would be nice to have a display snippet that simply renders the field content as a link.

So instead of
```
{{ h.link_to(data[field.field_name], rel=field.display_property, target='_blank') }}
```

this:
```
{{ h.link_to(data[field.field_name], rel=data[field.field_name], target='_blank') }}
```

does that make sense?

**Comment by wardi** [comment]
yes, that makes a lot more sense

**Comment by florianm** [comment]
The link back to the dataset page is an answer to the question asked on the CKAN mailing list re persistent dataset url.

I'll send you a PR tomorrow (time permitting) if you could let me know your preferred template snippet name for 
* render contents as link to dataset page (current behaviour)
* render contents as link to contents

**Comment by florianm** [comment]
@wardi sorry for the delay, the [fix](https://github.com/florianm/ckanext-scheming/blob/master/ckanext/scheming/templates/scheming/display_snippets/link.html) is to repeat the first argument:
```
{{ h.link_to(data[field.field_name], data[field.field_name], rel=field.display_property, target='_blank') }}
```
