### ISSUE TITLE
organisation field doesn't show selected organisation text

### ISSUE THREAD

**Issue by reneenoble** [open-data/ckanext-scheming#93]
Hi I'm using ckan 2.4 just trying to display the ckan_dataset schema provided in the package.  

When I go to select an organisation from the drop down (or there an organisation already selected as I have started making a dataset within the organisation) the selected organisation doesn't show up in the box.  It is definitely selected, as can be seen in the developer tools (where the selected option updates) and the dataset can be create and shows up under the correct organisation.  But the text just isn't showing up, it just remains blank.

Thanks,
Renee

**Comment by wardi** [comment]
I'm not sure I understand, is this a UI-only issue? Would you send a screenshot?

**Comment by reneenoble** [comment]
Hi Ian,


Yeah I think some javascript is broken for the manage dataset interface.  I'd try and fix it but javascript is not my forte.


Ok a screen shot is attached that shows what it looks like after I have clicked on an an organisation from the drop down list.  You can see I've selected "test1" as the organisation in the developer tools on the right, but the field box where it should display is empty.


To check it out yourself go here: http://52.64.153.184/dataset/edit/second-title
and log in with
username: help
password: pass

Then look at the field for organisation and select an organisation.  It won't display the name you select.  But you can tell it's been selected in the developer tools.

This also occurs when you have more organisations available in the drop down menu, you can see the field update in the dev tools if you click different options, but still no text appears in the box.

I should note that you are still able to create the dataset because it is technically selected.  It's just the display that's broken.

Thanks a bundle!
Renee

________________________________

**Comment by reneenoble** [comment]
Let me know if there is any other info I can provide.

Thanks!

**Comment by wardi** [comment]
Do you mind comparing the html/JS generated with scheming vs. without to try to see why scheming is not working on 2.4?

**Comment by hkotkanen** [comment]
+1, experiencing the same issue.

Haven't looked into it very far, but I did find that it's caused by styling: the input-prepend class has font-size: 0 (see screenshot and sorry it's in Finnish). Overriding the font-size to something sensible fixes the problem, but I don't know how to fix it in the source.

It looks like the class was introduced in commit 9957fa04bcdff971ea29aba065e1c2cc6f0512c4.
![organization_fontsize_0](https://cloud.githubusercontent.com/assets/5655648/10612116/1ee39d40-7758-11e5-84cc-0e390674a9fd.png)

**Comment by wardi** [comment]
Why don't we just remove the class from the snippet? I was copying that class from the form macro, but I must have done it wrong.

**Comment by reneenoble** [comment]
Yeah can confirm fixed with forcing the font size to change in dev tools.  

Works once I remove the class too, so I'll go with that.  

Thanks!

**Comment by wardi** [comment]
Ok, please confirm that b5294e0 fixes this issue

**Comment by reneenoble** [comment]
Yep that's the fix I made.  

Just re-cloned the repo and that works.  :)

**Comment by hkotkanen** [comment]
Great thanks, issue fixed!
